//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    
    public enum Age : int
    {
        NewBorn = 2,
        Child = 10,
        Teenager = 20,
        YoungAdult = 40,
        Adult = 60,
        Old = 100
    }
}
